// last updte: may 24, 2026
use std::env;
use std::fs::{self, File};
use std::io::Write;
use std::process::Command;
use std::process::exit;
use std::time::{SystemTime, UNIX_EPOCH};

mod ast;
mod codegen;
mod lexer;
mod parser;
mod semantic;
mod symtable;

use symtable::ClassInfo;

const ANSI_GREEN: &str = "\x1b[32m";
const ANSI_RED: &str = "\x1b[31m";
const ANSI_RESET: &str = "\x1b[0m";

#[derive(PartialEq)]
enum OutputMode {
    ModeNormal,
    ModeOutputCpp,
    ModeOutputAssembly,
}

// Compile a single .riv file to C++ and output to 'out'
// If 'trusted' is true, skip semantic analysis (not used here tho)
fn compile_file(
    path: &str,
    out: &mut File,
    class_registry: &[ClassInfo],
    trusted: bool,
    temp_cpp: &str,
) {
    let source = match fs::read_to_string(path) {
        Ok(s) => s,
        Err(_) => {
            eprintln!("{}error: cannot read {}{}", ANSI_RED, path, ANSI_RESET);
            exit(1);
        }
    };

    let tokens = lexer::tokenize(&source);
    let mut parser = parser::Parser::new(tokens);

    match parser.parse_program() {
        Ok(program) => {
            if !trusted {
                let mut analyzer = semantic::SemanticAnalyzer::new(class_registry);
                analyzer.analyze(&program, path);
                if analyzer.has_errors() {
                    analyzer.print_errors(path);
                    let _ = fs::remove_file(temp_cpp);
                    exit(1);
                }
            }
            let mut code_gen = codegen::CodeGen::new(out, class_registry);
            code_gen.gen_program(&program);
        }
        Err(e) => {
            eprintln!(
                "{}{}:{}: error: {}{}",
                ANSI_RED, path, e.line, e.message, ANSI_RESET
            );
            let _ = fs::remove_file(temp_cpp);
            exit(1);
        }
    }
}

fn main() {
    let args: Vec<String> = env::args().collect();
    let argc = args.len();

    println!("--- Open RiverLang Compiler ---");

    if argc < 2 {
        println!("Usage: ./riverlang.exe <filename.riv> [--output-cpp] [--output-assembly]");
        exit(0);
    }

    let mut input_file: Option<String> = None;
    let mut mode = OutputMode::ModeNormal;

    let mut i = 1;
    while i < argc {
        if args[i] == "--output-cpp" {
            mode = OutputMode::ModeOutputCpp;
        } else if args[i] == "--output-assembly" {
            mode = OutputMode::ModeOutputAssembly;
        } else {
            if input_file.is_none() {
                input_file = Some(args[i].clone());
            } else {
                eprintln!(
                    "{}error: multiple input files specified{}",
                    ANSI_RED, ANSI_RESET
                );
                exit(1);
            }
        }
        i += 1;
    }

    // Madatory .riv extension, you can change it here
    let input_file_str = input_file.expect("no input file");
    if !input_file_str.ends_with(".riv") {
        eprintln!(
            "{}error: input file must have .riv extension{}",
            ANSI_RED, ANSI_RESET
        );
        exit(1);
    }

    // Extract class name from file name (without .riv)
    let class_name = input_file_str
        .trim_end_matches(".riv")
        .split(['/', '\\'])
        .last()
        .unwrap()
        .to_string();

    let cpp_outname = format!("{}.cpp", class_name);
    let exe_outname = format!("{}.exe", class_name);
    let asm_outname = format!("{}.s", class_name);
    let temp_cpp: String;
    let mut out: File;

    if mode == OutputMode::ModeOutputCpp {
        out = File::create(&cpp_outname).unwrap_or_else(|_| {
            eprintln!(
                "{}error: cannot create output file: {}{}",
                ANSI_RED, cpp_outname, ANSI_RESET
            );
            exit(1);
        });
        temp_cpp = cpp_outname.clone();
    } else {
        let pid = std::process::id();
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();
        temp_cpp = format!("_rl_temp_{}_{}.cpp", pid, timestamp);
        out = File::create(&temp_cpp).unwrap_or_else(|_| {
            eprintln!(
                "{}error: cannot create temporary C++ file{}",
                ANSI_RED, ANSI_RESET
            );
            exit(1);
        });
    }

    println!("[INFO] Writing C++ code to {}...", temp_cpp);

    // Write common C++ includes
    writeln!(out, "/* Generated by RiverLang Compiler */").unwrap();
    writeln!(out, "#include <iostream>").unwrap();
    writeln!(out, "#include <string>").unwrap();
    writeln!(out, "#include <memory>").unwrap();
    writeln!(out, "#include <vector>").unwrap();
    writeln!(out, "#include <algorithm>").unwrap();
    writeln!(out, "#include <cstdlib>").unwrap();
    writeln!(out, "#include <cstdio>").unwrap();
    writeln!(out, "#include <cstdio>").unwrap();
    writeln!(out, "#define print(...) printf(__VA_ARGS__)").unwrap();
    writeln!(
        out,
        "#define println(...) printf(__VA_ARGS__); printf(\"\\n\")"
    ).unwrap();
    writeln!(out).unwrap();

    // Empty class registry, no pre‑declared classes
    let class_registry: Vec<ClassInfo> = Vec::new();

    // Compile the input file (not trusted, so semantic analysis runs)
    compile_file(&input_file_str, &mut out, &class_registry, false, &temp_cpp);

    // Generate the main function that calls the user's main method
    writeln!(out, "\nint main(int argc, char* argv[]) {{").unwrap();
    writeln!(out, "    try {{").unwrap();
    writeln!(out, "        return {}::main(argc, argv);", class_name).unwrap();
    writeln!(out, "    }} catch (const std::exception& e) {{").unwrap();
    writeln!(
        out,
        "        std::cerr << \"Error: \" << e.what() << std::endl;"
    )
    .unwrap();
    writeln!(out, "        return 1;").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();

    drop(out);

    if mode == OutputMode::ModeOutputCpp {
        println!(
            "{}C++ code generated: {}{}",
            ANSI_GREEN, cpp_outname, ANSI_RESET
        );
        exit(0);
    } else if mode == OutputMode::ModeOutputAssembly {
        println!("[INFO] Generating assembly: {}", asm_outname);
        let status = Command::new("g++")
            .args(&["-std=c++17", "-S", &temp_cpp, "-o", &asm_outname])
            .status();
        let _ = fs::remove_file(&temp_cpp);
        match status {
            Ok(s) if s.success() => {
                println!(
                    "{}Assembly output: {}{}",
                    ANSI_GREEN, asm_outname, ANSI_RESET
                );
            }
            _ => {
                eprintln!("{}BUILD FAILED{}", ANSI_RED, ANSI_RESET);
                exit(1);
            }
        }
        exit(0);
    } else {
        println!("[INFO] Building {}...", exe_outname);
        let status = Command::new("g++")
            .args(&["-std=c++17", &temp_cpp, "-o", &exe_outname])
            .status();
        let _ = fs::remove_file(&temp_cpp);
        if status.map(|s| s.success()).unwrap_or(false) {
            println!("{}BUILD SUCCESS: {}{}", ANSI_GREEN, exe_outname, ANSI_RESET);
        } else {
            eprintln!("{}BUILD FAILED{}", ANSI_RED, ANSI_RESET);
            exit(1);
        }
        exit(0);
    }
}
